// Code generated by "stringer -type=JoinType -linecomment"; DO NOT EDIT.

package jointoy

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InnerJoinType-0]
	_ = x[LeftJoinType-1]
	_ = x[CrossJoinType-2]
	_ = x[SemiJoinType-3]
	_ = x[AntiJoinType-4]
	_ = x[FullJoinType-5]
}

const _JoinType_name = "InnerLeftCrossSemiAntiFull"

var _JoinType_index = [...]uint8{0, 5, 9, 14, 18, 22, 26}

func (i JoinType) String() string {
	if i >= JoinType(len(_JoinType_index)-1) {
		return "JoinType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _JoinType_name[_JoinType_index[i]:_JoinType_index[i+1]]
}
